language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - vanesa.paniegos@alumnos.upm.es
script:
#Test unitario y de integracion en develop
- mvn verify
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
- mvn sonar:sonar -Dsonar.organization=vpaniego-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR
